# 初始化映射字典
NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

# Fast Image Saver 节点
from .fast_image_saver import NODE_CLASS_MAPPINGS as FAST_SAVER_MAPPINGS
from .fast_image_saver import NODE_DISPLAY_NAME_MAPPINGS as FAST_SAVER_DISPLAY_MAPPINGS
NODE_CLASS_MAPPINGS.update(FAST_SAVER_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(FAST_SAVER_DISPLAY_MAPPINGS)

# Mask Blender 节点
from .mask_blender import NODE_CLASS_MAPPINGS as MASK_MAPPINGS
from .mask_blender import NODE_DISPLAY_NAME_MAPPINGS as MASK_DISPLAY_MAPPINGS
NODE_CLASS_MAPPINGS.update(MASK_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MASK_DISPLAY_MAPPINGS)

# URLLoader 节点 - 图像加载
from .url_image_loader import NODE_CLASS_MAPPINGS as URL_IMAGE_NODES
from .url_image_loader import NODE_DISPLAY_NAME_MAPPINGS as URL_IMAGE_DISPLAY_NAMES
NODE_CLASS_MAPPINGS.update(URL_IMAGE_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(URL_IMAGE_DISPLAY_NAMES)

# URLLoader 节点 - 工作流控制
from .workflow_control_nodes import NODE_CLASS_MAPPINGS as WORKFLOW_CONTROL_NODES
from .workflow_control_nodes import NODE_DISPLAY_NAME_MAPPINGS as WORKFLOW_CONTROL_DISPLAY_NAMES
NODE_CLASS_MAPPINGS.update(WORKFLOW_CONTROL_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(WORKFLOW_CONTROL_DISPLAY_NAMES)

# Mask to SEGS Advanced 节点
from .mask_to_segs_advanced import NODE_CLASS_MAPPINGS as MASK_SEGS_MAPPINGS
from .mask_to_segs_advanced import NODE_DISPLAY_NAME_MAPPINGS as MASK_SEGS_DISPLAY_MAPPINGS
NODE_CLASS_MAPPINGS.update(MASK_SEGS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MASK_SEGS_DISPLAY_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

# Inpaint Nodes - Enhanced inpaint crop, stitch, and control
from .txkbf_inpaint_nodes import NODE_CLASS_MAPPINGS as INPAINT_MAPPINGS
from .txkbf_inpaint_nodes import NODE_DISPLAY_NAME_MAPPINGS as INPAINT_DISPLAY_MAPPINGS
NODE_CLASS_MAPPINGS.update(INPAINT_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(INPAINT_DISPLAY_MAPPINGS)
